services:
  - type: web
    name: Offers365-app
    env: node
    region: frankfurt
    buildCommand: npm install && npm run server:build && npm run expo:static:build
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Offers365-db
          property: connectionString